version: '3.3'

services:
  apache:
    build: .
    ports:
      - 8080:80
    volumes:
      - apache_data:/var/www/html
    depends_on:
      - phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8888:80
    volumes:
      - phpmyadmin_data:/sessions
    depends_on:
      - mysql
  mysql:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABSE: delicious
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  db_data:
  phpmyadmin_data:
  apache_data:
