version: '3.3'

volumes:
  db-data:

services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: delicious
      MYSQL_DATABASE: delicious
      MYSQL_USER: delicious
      MYSQL_PASSWORD: delicious
    volumes:
      - db-data:/var/lib/mysql
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
